"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't(puq$0rvl88kd^7w6ud3kro^r6-=o#&*m%%$-a=4$i0&pynr1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    # 'paypal.standard.ipn',
    'paypal.standard',
    'paypal.pro',

)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'abctest',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = 'https://www.mindcreature.com/mysite/public/static/'
STATIC_ROOT = '/home/webtunix/www.mindcreature.com/mysite/public/static/'


MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
LOGIN_REDIRECT_URL = '/'



EMAIL_HOST = 'smtp.sendgrid.net'  # since you are using a gmail account
EMAIL_PORT = 587  # Gmail SMTP port for TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@mindcreature.com'
EMAIL_HOST_PASSWORD = 'mind@123'
DEFAULT_FROM_EMAIL = 'info@mindcreature.com'
#
#
PAYPAL_TEST = False
PAYPAL_RECEIVER_EMAIL = 'onlinemindcreature@gmail.com'
PAYPAL_WPP_USER = "onlinemindcreature_api1.gmail.com"
PAYPAL_WPP_PASSWORD = "27FCWKJQLFR7LKRC"
PAYPAL_WPP_SIGNATURE = "AGFVxUIykOKcJK5-Mgsj9FyjAPA9Ang5tkLZGiGr-gPclN9T7Y.uC3g-"

# # TODO - THESE MUST BE SET
# RESOURCES_DIR = '/media/shared/src/django-paypal-store-example/samplesite/resources/'
# PAYPAL_PDT_TOKEN = '*** PAYPAY PDT TOKEN ***'
# PAYPAL_EMAIL = '*** PAYPAY EMAIL ***'
PAYPAL_RETURN_URL = 'http://127.0.0.1:8000'



# # sandbox
# PAYPAL_URL = 'https://www.sandbox.paypal.com/au/cgi-bin/webscr'
# PAYPAL_PDT_URL = 'https://www.sandbox.paypal.com/au/cgi-bin/webscr'



PAYPAL_URL = 'https://www.paypal.com/au/cgi-bin/webscr'
PAYPAL_PDT_URL = 'https://www.paypal.com/au/cgi-bin/webscr'



