# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BECOME_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BECOME_Contact',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('discription', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='carporate_traning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('primary_role', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carporate_traning',
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('video_link', models.CharField(blank=True, max_length=500, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('curricalum', models.TextField(blank=True, null=True)),
                ('course_assign_time', models.CharField(blank=True, max_length=100, null=True)),
                ('course_assign_description', models.TextField(blank=True, null=True)),
                ('project_time', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('life_time_access', models.TextField(blank=True, null=True)),
                ('support', models.TextField(blank=True, null=True)),
                ('get_certified', models.TextField(blank=True, null=True)),
                ('trending', models.CharField(blank=True, max_length=10, null=True)),
                ('popular', models.CharField(blank=True, max_length=10, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion', models.CharField(max_length=1000)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='free_esources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'free_esources',
            },
        ),
        migrations.CreateModel(
            name='onlinecourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.CharField(max_length=100)),
                ('month1', models.CharField(max_length=100)),
                ('day1', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=100)),
                ('date2', models.CharField(max_length=100)),
                ('month2', models.CharField(max_length=100)),
                ('day2', models.CharField(max_length=100)),
                ('price2', models.CharField(max_length=100)),
                ('date3', models.CharField(max_length=100)),
                ('month3', models.CharField(max_length=100)),
                ('day3', models.CharField(max_length=100)),
                ('price3', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'db_table': 'onlinecourse',
            },
        ),
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pdf', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('video_link', models.CharField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'db_table': 'pdf',
            },
        ),
        migrations.CreateModel(
            name='promecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'db_table': 'promecode',
            },
        ),
        migrations.CreateModel(
            name='REQUIREMENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('skype', models.CharField(blank=True, max_length=200, null=True)),
                ('hours', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'REQUIREMENTS',
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('discription', models.TextField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('suscribes', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'subscribe',
            },
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('about', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='uploads')),
                ('facebook', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('youtube', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teachers'),
        ),
        migrations.AddField(
            model_name='carporate_traning',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categories'),
        ),
        migrations.AddField(
            model_name='carporate_traning',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AddField(
            model_name='blog',
            name='categories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories'),
        ),
    ]
