# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instamojo_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Purpose', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instamojo_temp',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('item_name', models.IntegerField()),
                ('item_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
