# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_instamojo_temp_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
