# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171031_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instamojo_temp',
        ),
    ]
