# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20171031_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='instamojo_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('payment_request_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instamojo_payment',
            },
        ),
    ]
