# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_instamojo_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instamojo_payment_done',
            name='payment_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='instamojo_payment_done',
            name='payment_request_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
